django-empty-auth/newproject/apps/account/urls.py
from django.core.urlresolvers import reverse_lazy
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import login, logout

from forms import CustomAuthenticationForm

urlpatterns = patterns('',
    url(r'^logout$',
        logout,
        {'next_page': reverse_lazy('homepage')},
        name='logout'),
    url(r'^login$',
        login,
        {'template_name': 'account/login.html',
        'authentication_form': CustomAuthenticationForm}, 
        name='login'),
    url(r'^password-change/$',
        'django.contrib.auth.views.password_change',
        {'template_name': 'account/password_change.html',
         'post_change_redirect': reverse_lazy('homepage')}, 
        name='password-change'),
)

django-empty-auth/newproject/apps/main/urls.py
from django.core.urlresolvers import reverse_lazy
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
)

django-empty-auth/newproject/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib import admin

from newproject.apps.main.views import MainPageView
from newproject.apps.account.views import CustomRegistrationView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', MainPageView.as_view(), name='homepage'),
    url(r'^register/$',
        CustomRegistrationView.as_view(),
        name='register'),
    url(r'^register/complete/$',
        TemplateView.as_view(template_name='registration/registration_complete.html'),
        name='registration_complete'),
    url(r'^register/closed/$',
        TemplateView.as_view(template_name='registration/registration_closed.html'),
        name='registration_disallowed'),
    url(r'^account/', include('newproject.apps.account.urls', namespace='account')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^.*', include('newproject.apps.main.urls', namespace='main'))
)

urlpatterns += patterns(
    'django.views.static',
    (
        r'^static/(?P<path>.*)$',
        'serve',
        {
            'document_root': 'newproject/static/',
            'show_indexes': True
        }
    ))
urlpatterns += patterns(
    'django.views.static',
    (
        r'^media/(?P<path>.*)$',
        'serve',
        {
            'document_root': 'newproject/media/',
            'show_indexes': True
        }
    ))

django-empty-auth/newproject/apps/account/models.py
from django.contrib.auth.models import User, BaseUserManager, AbstractBaseUser
from django.db import models

class CustomUserManager(BaseUserManager):
  def create_user(self, email, password):
    user = CustomUser(username=email, email=email)
    user.set_password(password)
    user.is_active = True
    user.save()

    return user

class CustomUser(User):
  """
  CustomUser not needed, but created with vision of expanding model
  in the future
  """
  objects = CustomUserManager()

  def __str__(self):
    return 'pk=%s username=%s, email=%s' % (self.pk, self.username, self.email)

django-empty-auth/newproject/apps/main/models.py
from django.db import models

# Create your models here.

django-empty-auth/newproject/apps/account/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _

from registration.forms import RegistrationFormUniqueEmail

from newproject.apps.account import models

import re

class CustomAuthenticationForm(AuthenticationForm):
  username = forms.CharField(
      max_length=255,
      label=u'E-mail')

class RegistrationFormUniqueEmailAndUsername(RegistrationFormUniqueEmail):
  username = forms.CharField(required=False, widget=forms.HiddenInput())

django-empty-auth/newproject/apps/account/views.py
from django.contrib import messages
from django.conf import settings
from django.contrib.auth import authenticate

from registration import signals
from registration.views import RegistrationView as BaseRegistrationView

from models import CustomUser
from forms import RegistrationFormUniqueEmailAndUsername
from newproject import settings

class CustomRegistrationView(BaseRegistrationView):
  """
  A registration backend which implements the simplest possible
  workflow: a user supplies an email, email address and password
  (the bare minimum for a useful account), and is immediately signed
  up and logged in).
  """
  form_class = RegistrationFormUniqueEmailAndUsername

  def register(self, request, **cleaned_data):
    email, password = cleaned_data['email'], cleaned_data['password1']
    CustomUser.objects.create_user(email, password)

    new_user = authenticate(username=email, password=password)
    signals.user_registered.send(sender=self.__class__,
                                 user=new_user,
                                 request=request)
    return new_user

  def registration_allowed(self, request):
    """
    Indicate whether account registration is currently permitted,
    based on the value of the setting ``REGISTRATION_OPEN``. This
    is determined as follows:

    * If ``REGISTRATION_OPEN`` is not specified in settings, or is
    set to ``True``, registration is permitted.

    * If ``REGISTRATION_OPEN`` is both specified and set to
    ``False``, registration is not permitted.
    """
    return getattr(settings, 'REGISTRATION_OPEN', True)

  def get_context_data(self, *args, **kwargs):
    context = super(CustomRegistrationView, self).get_context_data(*args, **kwargs)
    if 'next' in self.request.GET:
      context['next'] = self.request.GET['next']
    return context

  def get_success_url(self, *args, **kwargs):
    return 'registration_complete'

django-empty-auth/newproject/apps/main/views.py
from django.views.generic import TemplateView, FormView, UpdateView, View

# Create your views here.
class MainPageView(TemplateView):
  template_name='main/main.html'

django-empty-auth/newproject/templates/base.html
{% load compress %}
{% load cache %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="shortcut icon" href="/static/img/favicon.ico" type="image/x-icon">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="og:image" content="/static/img/logo.png" />
    <meta name="description" content="project-description" />
    <script src="https://code.jquery.com/jquery-1.9.1.js"></script>
    <title>NewProject</title>
    {% compress css %}
      <link type="text/css" href="/static/css/bootstrap.min.css" rel="stylesheet" />

      <link type="text/less" href="/static/less/main.less" rel="stylesheet" />
    {% endcompress %}
  </head>
  <body>
    {% block body %}
      <div class="navbar navbar-default">
        <div class="container">
          <div class="navbar-header">
            <a href="/" class="navbar-brand">NewProject</a>
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="navbar-collapse collapse" id="navbar-main">
            <ul class="nav navbar-nav navbar-right">
              <li>
                <a href="{% url 'homepage' %}">Home</a>
              </li>
              {% if request.user.is_authenticated %}
                <li class="dropdown">
                  <a href="#" class"dropdown-toggle" data-toggle="dropdown">{{ request.user.username }}</a>
                  <ul class="dropdown-menu">
                    <li>
                      <a href="{% url 'account:logout' %}">Logout</a>
                    </li>
                  </ul>
                </li>
              {% else %}
                <li>
                  <a href="{% url 'account:login' %}">Log In</a>
                </li>
                <li>
                  <a href="{% url 'register' %}">Sign Up</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
      <div class="container">
        {% block content %}
        {% endblock %}

        <div class="footer with-top-margin">
          <div class="row">
            <div class="col-xs-12">
              &copy; NewProject 2014
            </div>
          </div>
        </div>
      </div>
  
      {% compress js %}
        <script type="text/javascript" src="/static/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="/static/js/custom.js"></script>
        <script type="text/javascript">
          $(document).ready(function() {
            $('li.dropdown').bind('click', function() {
              $('#navbar-main').css('height', 'auto');
            });
          });
        </script>
      {% endcompress %}
    {% endblock %}
  </body>
</html>

django-empty-auth/newproject/templates/field.html
{# inc/field.html #}
{% load widget_tweaks %}
<div class="form-group {% if field.errors %}has-error{% endif %} {% if narrow %}narrow{% endif %}">
  {% if not hide_label %}
    <label class="control-label {% if close_label %}no-bottom-margin{% endif %}">
      {% if not hide_errors %}
        {% if field.errors %}
          {{field.errors}}
        {% endif %}
      {% endif %}
    </label>
  {% endif %}
  {% render_field field|add_class:"form-control" placeholder=field.label %}
</div>

django-empty-auth/newproject/templates/main/main.html
{% extends "base.html" %}

{% block content %}
<style type="text/css">
  @media (min-width: 768px) {
    .container {
      width:100%;
      max-width: 730px;
    }
  }
</style>
<div class="row">
  <div class="col-xs-12">
    <div class="jumbotron">
      <h1>New project</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec elementum velit vitae volutpat ullamcorper. Duis pharetra suscipit fringilla. Integer ac tincidunt justo.</p>
      <a href="#" class="btn btn-default btn-primary">Get started</a>
      <p class="italic smaller">..or <a href="#">learn more</a>.</p>
    </div>
  </div>
</div>
{% endblock %}